substitutions:
  _IMAGE_NAME: go-story

steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

  # Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      # 記憶體、CPU、同時連線數等可視需要調整
      - "--memory=512Mi"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
