substitutions:
  _IMAGE_NAME: go-story

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

