substitutions:
  _IMAGE_NAME: go-story
  _DEPLOY_REGION: asia-east1
  _PLATFORM: managed

steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

  # Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - "--region=${_DEPLOY_REGION}"
      - "--platform=${_PLATFORM}"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
